// src/pages/SettingsPage.vue
<template>
  <Layout>
    <div class="space-y-6">
      <!-- Page Header -->
      <div>
        <h1 class="text-2xl font-bold text-slate-900">Configuración</h1>
        <p class="text-slate-600 mt-1">
          Administra la configuración del sistema y preferencias.
        </p>
      </div>

      <!-- Settings Sections -->
      <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <!-- General Settings -->
        <div class="bg-white p-6 rounded-lg border border-slate-300">
          <h3 class="text-lg font-semibold text-slate-900 mb-4">Configuración General</h3>
          <div class="space-y-4">
            <div>
              <label class="block text-sm font-medium text-slate-700 mb-2">
                Nombre de la Empresa
              </label>
              <input
                type="text"
                value="CRM System"
                class="w-full px-3 py-2 border border-slate-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>
            <div>
              <label class="block text-sm font-medium text-slate-700 mb-2">
                Email de Contacto
              </label>
              <input
                type="email"
                value="contact@crmsystem.com"
                class="w-full px-3 py-2 border border-slate-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>
            <div>
              <label class="block text-sm font-medium text-slate-700 mb-2">
                Zona Horaria
              </label>
              <select class="w-full px-3 py-2 border border-slate-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500">
                <option>UTC-5 (Ecuador)</option>
                <option>UTC-3 (Argentina)</option>
                <option>UTC-6 (México)</option>
              </select>
            </div>
          </div>
        </div>

        <!-- Notification Settings -->
        <div class="bg-white p-6 rounded-lg border border-slate-300">
          <h3 class="text-lg font-semibold text-slate-900 mb-4">Notificaciones</h3>
          <div class="space-y-4">
            <div class="flex items-center justify-between">
              <div>
                <p class="text-sm font-medium text-slate-700">Email Notifications</p>
                <p class="text-xs text-slate-500">Recibir notificaciones por email</p>
              </div>
              <input type="checkbox" checked class="h-4 w-4 text-blue-600" />
            </div>
            <div class="flex items-center justify-between">
              <div>
                <p class="text-sm font-medium text-slate-700">Push Notifications</p>
                <p class="text-xs text-slate-500">Notificaciones en el navegador</p>
              </div>
              <input type="checkbox" class="h-4 w-4 text-blue-600" />
            </div>
            <div class="flex items-center justify-between">
              <div>
                <p class="text-sm font-medium text-slate-700">SMS Notifications</p>
                <p class="text-xs text-slate-500">Notificaciones por SMS</p>
              </div>
              <input type="checkbox" class="h-4 w-4 text-blue-600" />
            </div>
          </div>
        </div>

        <!-- User Management -->
        <div class="bg-white p-6 rounded-lg border border-slate-300">
          <h3 class="text-lg font-semibold text-slate-900 mb-4">Gestión de Usuarios</h3>
          <div class="space-y-4">
            <div class="flex items-center justify-between p-3 bg-slate-50 rounded-lg">
              <div class="flex items-center space-x-3">
                <div class="w-8 h-8 bg-blue-500 rounded-full flex items-center justify-center">
                  <span class="text-white text-sm font-medium">MG</span>
                </div>
                <div>
                  <p class="text-sm font-medium text-slate-900">María García</p>
                  <p class="text-xs text-slate-500">Admin</p>
                </div>
              </div>
              <button class="text-blue-600 text-sm hover:text-blue-800">Editar</button>
            </div>
            <div class="flex items-center justify-between p-3 bg-slate-50 rounded-lg">
              <div class="flex items-center space-x-3">
                <div class="w-8 h-8 bg-green-500 rounded-full flex items-center justify-center">
                  <span class="text-white text-sm font-medium">CR</span>
                </div>
                <div>
                  <p class="text-sm font-medium text-slate-900">Carlos Ruiz</p>
                  <p class="text-xs text-slate-500">Usuario</p>
                </div>
              </div>
              <button class="text-blue-600 text-sm hover:text-blue-800">Editar</button>
            </div>
            <button class="w-full py-2 px-4 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors">
              Agregar Usuario
            </button>
          </div>
        </div>

        <!-- System Info -->
        <div class="bg-white p-6 rounded-lg border border-slate-300">
          <h3 class="text-lg font-semibold text-slate-900 mb-4">Información del Sistema</h3>
          <div class="space-y-3">
            <div class="flex justify-between">
              <span class="text-sm text-slate-600">Versión:</span>
              <span class="text-sm font-medium text-slate-900">1.0.0</span>
            </div>
            <div class="flex justify-between">
              <span class="text-sm text-slate-600">Última Actualización:</span>
              <span class="text-sm font-medium text-slate-900">15 Ene 2024</span>
            </div>
            <div class="flex justify-between">
              <span class="text-sm text-slate-600">Base de Datos:</span>
              <span class="text-sm font-medium text-green-600">Conectada</span>
            </div>
            <div class="flex justify-between">
              <span class="text-sm text-slate-600">Almacenamiento:</span>
              <span class="text-sm font-medium text-slate-900">2.3 GB / 10 GB</span>
            </div>
          </div>
        </div>
      </div>

      <!-- Action Buttons -->
      <div class="flex justify-end space-x-4">
        <button class="px-4 py-2 border border-slate-300 text-slate-700 rounded-md hover:bg-slate-50 transition-colors">
          Cancelar
        </button>
        <button class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors">
          Guardar Cambios
        </button>
      </div>
    </div>
  </Layout>
</template>

<script setup lang="ts">
import Layout from '../components/layout/Layout.vue'
</script>

// src/pages/SettingsPage.tsx
import React, { useState } from 'react';
import { 
  User, 
  Bell, 
  Shield, 
  Palette, 
  Globe, 
  Database,
  CheckCircle 
} from '@phosphor-icons/react';
import { Card, CardHeader, CardTitle, CardContent, Button, Input } from '../components/ui';

const SettingsPage: React.FC = () => {
  const [notifications, setNotifications] = useState({
    email: true,
    push: false,
    sms: true,
  });

  const [profile, setProfile] = useState({
    name: 'Usuario Demo',
    email: 'usuario@ejemplo.com',
    company: 'Mi Empresa',
    timezone: 'America/Guayaquil',
  });

  const handleNotificationChange = (type: keyof typeof notifications) => {
    setNotifications(prev => ({
      ...prev,
      [type]: !prev[type]
    }));
  };

  const handleProfileChange = (field: keyof typeof profile, value: string) => {
    setProfile(prev => ({
      ...prev,
      [field]: value
    }));
  };

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div>
        <h1 className="text-2xl font-bold text-slate-900">Configuración</h1>
        <p className="text-slate-600 mt-1">
          Ajusta las preferencias del sistema y tu perfil.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Profile Settings */}
        <div className="lg:col-span-2 space-y-6">
          <Card variant="elevated">
            <CardHeader>
              <CardTitle className="flex items-center">
                <User size={20} className="mr-2" />
                Perfil de Usuario
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-2">
                    Nombre completo
                  </label>
                  <Input
                    value={profile.name}
                    onChange={(e) => handleProfileChange('name', e.target.value)}
                    placeholder="Tu nombre completo"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-2">
                    Email
                  </label>
                  <Input
                    type="email"
                    value={profile.email}
                    onChange={(e) => handleProfileChange('email', e.target.value)}
                    placeholder="tu@email.com"
                  />
                </div>
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-2">
                    Empresa
                  </label>
                  <Input
                    value={profile.company}
                    onChange={(e) => handleProfileChange('company', e.target.value)}
                    placeholder="Nombre de tu empresa"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-2">
                    Zona horaria
                  </label>
                  <select 
                    className="w-full px-3 py-2 border border-slate-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                    value={profile.timezone}
                    onChange={(e) => handleProfileChange('timezone', e.target.value)}
                  >
                    <option value="America/Guayaquil">Ecuador (GMT-5)</option>
                    <option value="America/Lima">Perú (GMT-5)</option>
                    <option value="America/Bogota">Colombia (GMT-5)</option>
                    <option value="America/Mexico_City">México (GMT-6)</option>
                  </select>
                </div>
              </div>

              <div className="pt-4">
                <Button variant="primary">
                  Guardar cambios
                </Button>
              </div>
            </CardContent>
          </Card>

          {/* Notifications */}
          <Card variant="elevated">
            <CardHeader>
              <CardTitle className="flex items-center">
                <Bell size={20} className="mr-2" />
                Notificaciones
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <p className="font-medium text-slate-900">Notificaciones por email</p>
                  <p className="text-sm text-slate-600">Recibe actualizaciones por correo electrónico</p>
                </div>
                <button
                  onClick={() => handleNotificationChange('email')}
                  className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${
                    notifications.email ? 'bg-blue-600' : 'bg-slate-200'
                  }`}
                >
                  <span
                    className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${
                      notifications.email ? 'translate-x-6' : 'translate-x-1'
                    }`}
                  />
                </button>
              </div>

              <div className="flex items-center justify-between">
                <div>
                  <p className="font-medium text-slate-900">Notificaciones push</p>
                  <p className="text-sm text-slate-600">Recibe notificaciones en el navegador</p>
                </div>
                <button
                  onClick={() => handleNotificationChange('push')}
                  className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${
                    notifications.push ? 'bg-blue-600' : 'bg-slate-200'
                  }`}
                >
                  <span
                    className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${
                      notifications.push ? 'translate-x-6' : 'translate-x-1'
                    }`}
                  />
                </button>
              </div>

              <div className="flex items-center justify-between">
                <div>
                  <p className="font-medium text-slate-900">SMS</p>
                  <p className="text-sm text-slate-600">Recibe alertas importantes por SMS</p>
                </div>
                <button
                  onClick={() => handleNotificationChange('sms')}
                  className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${
                    notifications.sms ? 'bg-blue-600' : 'bg-slate-200'
                  }`}
                >
                  <span
                    className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${
                      notifications.sms ? 'translate-x-6' : 'translate-x-1'
                    }`}
                  />
                </button>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Quick Settings */}
        <div className="space-y-6">
          <Card variant="elevated">
            <CardHeader>
              <CardTitle className="flex items-center">
                <Shield size={20} className="mr-2" />
                Seguridad
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              <Button variant="outline" className="w-full justify-start">
                Cambiar contraseña
              </Button>
              <Button variant="outline" className="w-full justify-start">
                Autenticación 2FA
              </Button>
              <Button variant="outline" className="w-full justify-start">
                Sesiones activas
              </Button>
            </CardContent>
          </Card>

          <Card variant="elevated">
            <CardHeader>
              <CardTitle className="flex items-center">
                <Palette size={20} className="mr-2" />
                Apariencia
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              <div>
                <p className="text-sm font-medium text-slate-700 mb-2">Tema</p>
                <select className="w-full px-3 py-2 border border-slate-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500">
                  <option>Claro</option>
                  <option>Oscuro</option>
                  <option>Automático</option>
                </select>
              </div>
            </CardContent>
          </Card>

          <Card variant="elevated">
            <CardHeader>
              <CardTitle className="flex items-center">
                <Database size={20} className="mr-2" />
                Sistema
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              <div className="flex items-center text-sm">
                <CheckCircle size={16} className="text-green-500 mr-2" />
                <span>Sistema actualizado</span>
              </div>
              <div className="text-xs text-slate-500">
                Versión 1.0.0
              </div>
              <Button variant="outline" size="sm" className="w-full">
                Verificar actualizaciones
              </Button>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
};

export { SettingsPage };
